PL/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Dashboard()
        {
            var token = Request.Cookies["AuthToken"];

            if (string.IsNullOrEmpty(token))
                return RedirectToAction("Login", "Login");

            ViewBag.Token = token;
            return View();
        }

    }
}

PL/Controllers/EmpleadoController.cs
using Azure;
using BL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Text;
using System.Text;

namespace PL.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly BL.City _city;
        private readonly BL.Education _education;
        private readonly BL.EverBenched _everBenched;
        private readonly BL.Gender _gender;
        private readonly BL.Empleado _empleado;


        public EmpleadoController(IConfiguration configuration, BL.City city, BL.Education education, BL.EverBenched everBenched, BL.Gender gender, Empleado empleado)
        {
            _configuration = configuration;
            _city = city;
            _education = education;
            _everBenched = everBenched;
            _gender = gender;
            _empleado = empleado;
        }

        [Authorize(Roles = "RRHH,Gerente")]
        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Empleado empleado = new ML.Empleado();
            empleado.Empleados = new List<object>();
            empleado.City = new ML.City();
            empleado.Education = new ML.Education();
            empleado.EverBenched = new ML.EverBenched();
            empleado.Gender = new ML.Gender();

            ML.Result result = _city.GetAll();
            ML.Result resultEducation = _education.GetAll();
            ML.Result resultEverBenched = _everBenched.GetAll();
            ML.Result ResultGender = _gender.GetAll();

            if (result.Correct && result.Objects != null)
            {
                empleado.City.Cities = result.Objects;
            }
            if (resultEducation.Correct && resultEducation.Objects != null)
            {
                empleado.Education.Educations = resultEducation.Objects;
            }
            if (resultEverBenched.Correct && resultEverBenched.Objects != null)
            {
                empleado.EverBenched.EverBenches = resultEverBenched.Objects;
            }
            if (ResultGender.Correct && ResultGender.Objects != null)
            {
                empleado.Gender.Genders = ResultGender.Objects;
            }
            try
            {
                using (var client = new HttpClient())
                {
                    string baseUrl = _configuration["ApiSettings:BaseUrl"];
                    client.BaseAddress = new Uri(baseUrl);

                    var token = Request.Cookies["AuthToken"];

                    client.DefaultRequestHeaders.Authorization =
                        new System.Net.Http.Headers.AuthenticationHeaderValue(
                            "Bearer", token
                        );

                    var response = client.PostAsJsonAsync("GetAll", empleado);

                    response.Wait();

                    if (response.Result.IsSuccessStatusCode)
                    {
                        var jsonResponse = response.Result.Content.ReadAsStringAsync().Result;
                        ML.Result resultApi = JsonConvert.DeserializeObject<ML.Result>(jsonResponse);

                        if (resultApi.Objects != null)
                        {
                            foreach (var item in resultApi.Objects)
                            {
                                ML.Empleado empleadoObj = JsonConvert.DeserializeObject<ML.Empleado>(item.ToString());
                                empleado.Empleados.Add(empleadoObj);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return View(empleado);

        }
        [Authorize(Roles = "RRHH,Gerente")]
        [HttpPost]
        public IActionResult GetAll(ML.Empleado empleado)
        {
            empleado.Empleados = new List<object>();
            empleado.City = new ML.City();
            empleado.Education = new ML.Education();
            empleado.EverBenched = new ML.EverBenched();
            empleado.Gender = new ML.Gender();

            ML.Result result = _city.GetAll();
            ML.Result resultEducation = _education.GetAll();
            ML.Result resultEverBenched = _everBenched.GetAll();
            ML.Result ResultGender = _gender.GetAll();

            if (result.Correct && result.Objects != null)
            {
                empleado.City.Cities = result.Objects;
            }
            if (resultEducation.Correct && resultEducation.Objects != null)
            {
                empleado.Education.Educations = resultEducation.Objects;
            }
            if (resultEverBenched.Correct && resultEverBenched.Objects != null)
            {
                empleado.EverBenched.EverBenches = resultEverBenched.Objects;
            }
            if (ResultGender.Correct && ResultGender.Objects != null)
            {
                empleado.Gender.Genders = ResultGender.Objects;
            }

            try
            {
                using (var client = new HttpClient())
                {
                    string baseUrl = _configuration["ApiSettings:BaseUrl"];
                    client.BaseAddress = new Uri(baseUrl);
                    var token = Request.Cookies["AuthToken"];

                    client.DefaultRequestHeaders.Authorization =
                        new System.Net.Http.Headers.AuthenticationHeaderValue(
                            "Bearer", token
                        );
                    var response = client.PostAsJsonAsync("GetAll", empleado);

                    response.Wait();

                    if (response.Result.IsSuccessStatusCode)
                    {
                        var jsonResponse = response.Result.Content.ReadAsStringAsync().Result;
                        ML.Result resultApi = JsonConvert.DeserializeObject<ML.Result>(jsonResponse);

                        if (resultApi.Objects != null)
                        {
                            foreach (var item in resultApi.Objects)
                            {
                                ML.Empleado empleadoObj = JsonConvert.DeserializeObject<ML.Empleado>(item.ToString());
                                empleado.Empleados.Add(empleadoObj);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }

            return View(empleado);
        }

        [Authorize(Roles = "RRHH")]
        [HttpGet]
        public IActionResult Delete(int IdEmpleado)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    string baseUrl = _configuration["ApiSettings:BaseUrl"];
                    client.BaseAddress = new Uri(baseUrl);
                    var token = Request.Cookies["AuthToken"];

                    client.DefaultRequestHeaders.Authorization =
                        new System.Net.Http.Headers.AuthenticationHeaderValue(
                            "Bearer", token
                        );
                    client.DeleteAsync($"Delete/{IdEmpleado}").Wait();

                    var task = client.DeleteAsync($"Delete/{IdEmpleado}");
                    task.Wait();

                    if (task.Result.IsSuccessStatusCode)
                    {
                        var jsonResponse = task.Result.Content.ReadAsStringAsync().Result;
                        ML.Result resultApi = JsonConvert.DeserializeObject<ML.Result>(jsonResponse);

                        if (resultApi.Correct)
                        {
                            return RedirectToAction("GetAll");
                        }

                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
            }

            return RedirectToAction("GetAll");
        }

        [Authorize(Roles = "RRHH")]
        [HttpGet]
        public ActionResult Formulario(int? IdEmpleado)
        {
            ML.Empleado empleado = new ML.Empleado
            {
                City = new ML.City(),
                Education = new ML.Education(),
                Gender = new ML.Gender(),
                EverBenched = new ML.EverBenched()
            };

            if (IdEmpleado.HasValue)
            {
                try
                {
                    using (var client = new HttpClient())
                    {
                        string baseUrl = _configuration["ApiSettings:BaseUrl"];
                        client.BaseAddress = new Uri(baseUrl);
                        var token = Request.Cookies["AuthToken"];

                        client.DefaultRequestHeaders.Authorization =
                            new System.Net.Http.Headers.AuthenticationHeaderValue(
                                "Bearer", token
                            );
                        var response = client.GetAsync($"GetById/{IdEmpleado.Value}").Result;
                        if (response.IsSuccessStatusCode)
                        {
                            var jsonResponse = response.Content.ReadAsStringAsync().Result;
                            ML.Result resultApi = JsonConvert.DeserializeObject<ML.Result>(jsonResponse);



                            if (resultApi.Object != null)
                            {
                                empleado = JsonConvert.DeserializeObject<ML.Empleado>(resultApi.Object.ToString());

                              
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.Message;
                }
            }

PL/Views/Shared/_Layout.cshtml
@{
    // var token = Context.Session.GetString("JWT");
    // bool autenticado = !string.IsNullOrEmpty(token);
    bool autenticado = User.Identity?.IsAuthenticated ?? false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">

        @if (autenticado)
        {
           

            <li class="nav-item">
                <a class="nav-link text-dark"
                   asp-controller="Empleado" asp-action="GetAll">
                    Empleados
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-dark"
                   asp-controller="Empleado" asp-action="CargaMasiva">
                    Carga Masiva
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-dark"
                   asp-controller="Dashboard" asp-action="Dashboard">
                    Dashboard
                </a>
            </li>

            <li class="nav-item ms-auto">
                <a class="nav-link text-danger"
                   asp-controller="Login" asp-action="Logout">
                    Logout
                </a>
            </li>
        }
        else
        {
            <li class="nav-item ms-auto">
                <a class="nav-link text-primary"
                   asp-controller="Login" asp-action="Login">
                    Login
                </a>
            </li>
        }
    </ul>
</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>